/**
 * The manual-verification checklist.
 *
 * This is a first-class output, not a disclaimer. Automated rules cover a
 * minority of WCAG — 57% of issue instances by volume on Deque's own numbers,
 * but only ~31% of the 55 AA criteria have any ACT-approved automated rule and
 * ~13% are reliably flagged. Nine A/AA criteria cannot be meaningfully tested by
 * any tool.
 *
 * Items are generated from what was actually on the page, so the list is short
 * and specific rather than a generic wall of text. An empty page gets three
 * items; a page with a form, images and a dialog gets the ones that apply.
 */

/** Always relevant, whatever the page contains. */
const UNIVERSAL = [
  {
    id: 'assistive-technology',
    sc: null,
    text: 'Test with a real screen reader (NVDA or JAWS on Windows, VoiceOver on macOS/iOS).',
    why:
      'No automated tool, and no simulator, reproduces real AT behaviour — NVDA, JAWS and ' +
      'VoiceOver diverge from each other and from the specification.',
  },
  {
    id: 'focus-order-logic',
    sc: '2.4.3',
    text: 'Tab through the page and confirm the focus order is logical, not merely present.',
    why:
      'a11y-loop can see that focus moves and where it goes, but whether the sequence makes ' +
      'sense for this content is a human judgment.',
  },
  {
    id: 'keyboard-only-walkthrough',
    sc: '2.1.1',
    text: 'Complete the page’s main task using only the keyboard.',
    why:
      'Automated checks probe individual controls; they do not know what the user is trying ' +
      'to accomplish.',
  },
];

/**
 * Conditional items, keyed by a fact on the page.
 * `when` receives the page inventory and returns whether the item applies.
 */
const CONDITIONAL = [
  {
    id: 'alt-text-quality',
    sc: '1.1.1',
    when: (f) => f.images > 0,
    text: (f) =>
      `Confirm the alt text on ${f.images} image${f.images === 1 ? '' : 's'} is accurate and ` +
      'useful, and that decorative images use alt="" rather than a description.',
    why:
      'Automation can only see whether alt text exists. alt="decorative image" passes every ' +
      'automated rule and is worse than alt="". If any alt text was generated by an AI, treat ' +
      'it as a draft that a human must confirm.',
  },
  {
    id: 'form-error-quality',
    sc: '3.3.3',
    when: (f) => f.formFields > 0,
    text: (f) =>
      `Submit the form with ${f.formFields} field${f.formFields === 1 ? '' : 's'} in an invalid ` +
      'state and confirm each error is announced, identifies the field, and says how to fix it.',
    why:
      'SC 3.3.1 and 3.3.3 are about whether an error message is actionable, which no tool can ' +
      'assess. Error states also usually only exist after interaction — audit them with ' +
      '--interact.',
  },
  {
    id: 'label-clarity',
    sc: '2.4.6',
    when: (f) => f.formFields > 0,
    text: 'Confirm every field label describes what to enter, not just that a label exists.',
    why: 'A label of "Field 1" satisfies every automated rule and tells the user nothing.',
  },
  {
    id: 'link-purpose',
    sc: '2.4.4',
    when: (f) => f.links > 0,
    text: 'Read each link text out of context and confirm the destination is still clear.',
    why:
      'SC 2.4.4 permits vague link text when the surrounding context supplies the purpose — ' +
      'whether it does is a judgment call.',
  },
  {
    id: 'heading-semantics',
    sc: '1.3.1',
    when: (f) => f.headings > 0,
    text: 'Confirm the heading structure describes the content hierarchy, not the visual sizes.',
    why:
      'Automation can detect skipped levels but not whether the outline reflects the actual ' +
      'structure of the page.',
  },
  {
    id: 'media-alternatives',
    sc: '1.2.2',
    when: (f) => f.videos > 0 || f.audios > 0,
    text: 'Check caption accuracy, and provide a transcript and (for video) audio description.',
    why:
      'Caption and transcript quality is entirely a human assessment; the presence of a track ' +
      'element says nothing about whether it is correct or synchronised.',
  },
  {
    id: 'table-reflow-meaning',
    sc: '1.4.10',
    when: (f) => f.tables > 0,
    text: 'Confirm the table still conveys its meaning at a 320px viewport.',
    why:
      'SC 1.4.10 excepts content requiring two-dimensional layout. Whether a given table ' +
      'qualifies, and whether it remains understandable, needs a person.',
  },
  {
    id: 'aria-appropriateness',
    sc: '4.1.2',
    when: (f) => f.ariaAttributes > 0,
    text: (f) =>
      `Review the ${f.ariaAttributes} ARIA attribute${f.ariaAttributes === 1 ? '' : 's'} on this ` +
      'page: is each one appropriate, or merely valid?',
    why:
      'Pages using ARIA average more accessibility errors than pages without it (WebAIM ' +
      'Million 2026: 59.1 vs 42.0). A role is a promise — role="button" commits to the full ' +
      'keyboard behaviour of a button. No ARIA is better than bad ARIA.',
  },
  {
    id: 'dialog-behaviour',
    sc: '2.1.2',
    when: (f) => f.dialogs > 0,
    text: 'Confirm each dialog announces itself on open and describes how to dismiss it.',
    why:
      'a11y-loop tests the focus trap, Escape, and focus return mechanically. Whether the ' +
      'dialog is comprehensible when announced is a screen-reader test.',
  },
  {
    id: 'motion-essential',
    sc: '2.3.3',
    when: (f) => f.animations > 0,
    text: 'Confirm any animation that survives prefers-reduced-motion is genuinely essential.',
    why: 'The "essential" exception cannot be evaluated automatically.',
  },
  {
    id: 'color-not-only-cue',
    sc: '1.4.1',
    when: (f) => f.links > 0 || f.formFields > 0,
    text: 'Confirm colour is never the only way information is conveyed.',
    why:
      'SC 1.4.1 is one of the criteria no tool can test: recognising that "the required fields ' +
      'are in red" needs comprehension of the content.',
  },
  {
    id: 'focus-not-obscured',
    sc: '2.4.11',
    when: (f) => f.stickyElements > 0,
    text: 'Tab through the page and confirm the focused element is never hidden behind sticky or fixed content.',
    why:
      'SC 2.4.11 (new in WCAG 2.2) has no automated rule. This page has position:sticky or ' +
      'position:fixed elements, which are the usual cause.',
  },
];

/**
 * Engine limitations worth restating when the relevant rule actually turned up
 * in axe's `incomplete` array — each one is a place axe knows it does not know.
 */
const ENGINE_NOTES = {
  'color-contrast': {
    id: 'contrast-undeterminable',
    sc: '1.4.3',
    text:
      'Check the contrast of the elements axe could not measure by hand (WebAIM Contrast ' +
      'Checker, or a11y-loop contrast <fg> <bg>).',
    why:
      'axe gives up on background images, gradients, pseudo-element backgrounds and ' +
      'foreground opacity or occlusion, and reports them as incomplete. A computed ratio of ' +
      '1:1 is the usual tell.',
  },
  'color-contrast-enhanced': {
    id: 'contrast-enhanced-undeterminable',
    sc: '1.4.6',
    text: 'Check the enhanced-contrast candidates axe could not measure by hand.',
    why: 'Same limitation as SC 1.4.3: computed backgrounds defeat the measurement.',
  },
  'frame-tested': {
    id: 'cross-origin-frames',
    sc: null,
    text: 'Audit the contents of cross-origin iframes separately, at their own origin.',
    why:
      'axe cannot inject into a frame it cannot script, so that content was not tested at ' +
      'all — its absence from this report means nothing.',
  },
  'aria-hidden-focus': {
    id: 'aria-hidden-focus-review',
    sc: '4.1.2',
    text: 'Confirm that elements inside aria-hidden containers really are unreachable.',
    why: 'axe could not determine focusability for some of these elements.',
  },
  'link-in-text-block': {
    id: 'link-distinguishable',
    sc: '1.4.1',
    text: 'Confirm links inside body text are distinguishable without relying on colour alone.',
    why: 'axe could not determine the surrounding text colour for some links.',
  },
  'target-size': {
    id: 'target-size-axe',
    sc: '2.5.8',
    text: 'Re-measure the targets axe flagged for size by hand.',
    why:
      'axe ships target-size disabled by default because of a documented false-positive trail ' +
      'with overlapping and translucent targets. a11y-loop enables it, and always reports it ' +
      'as needs-review.',
  },
};

/** Checks that are never automated at all, listed so their absence is not read as a pass. */
const NEVER_AUTOMATED = [
  {
    id: 'hover-focus-contrast',
    sc: '1.4.11',
    text: 'Check the contrast of hover and focus states.',
    why:
      'No engine checks state contrast unless the state is driven and re-scanned. Use ' +
      '--interact to add hover and focus states to the audit.',
  },
];

/**
 * @param {object} input
 * @param {object} input.facts page inventory from `surveyPageFacts`
 * @param {string[]} [input.incompleteRuleIds] axe rules that returned incomplete
 * @param {boolean} [input.statesRun] whether any --interact states were audited
 * @returns {Array<{id:string, sc:string|null, text:string, why:string}>}
 */
export function buildChecklist({ facts = {}, incompleteRuleIds = [], statesRun = [] } = {}) {
  const inventory = {
    images: 0,
    formFields: 0,
    links: 0,
    headings: 0,
    videos: 0,
    audios: 0,
    tables: 0,
    iframes: 0,
    dialogs: 0,
    ariaAttributes: 0,
    animations: 0,
    stickyElements: 0,
    ...facts,
  };

  const items = [...UNIVERSAL];

  for (const item of CONDITIONAL) {
    if (!item.when(inventory)) continue;
    items.push({
      id: item.id,
      sc: item.sc,
      text: typeof item.text === 'function' ? item.text(inventory) : item.text,
      why: item.why,
    });
  }

  const seen = new Set(items.map((i) => i.id));
  for (const ruleId of incompleteRuleIds) {
    const note = ENGINE_NOTES[ruleId];
    if (note && !seen.has(note.id)) {
      items.push(note);
      seen.add(note.id);
    }
  }

  // If no interaction states were audited, hover/focus contrast is untested.
  if (statesRun.length === 0) {
    for (const item of NEVER_AUTOMATED) {
      if (!seen.has(item.id)) items.push(item);
    }
  }

  return items;
}
